### ISSUE TITLE
Argument: endpoint

### ISSUE THREAD

**Issue by sudojunior** [sudojunior/access-check#15]
**_Future_**

Links back to #5 with enterprise site admin.

```yml
# predefined jobs / steps
- uses: sudojunior/access-check@main
  with:
    endpoint: https://git.example.com/api # defaulting to https://api.github.com
```
